//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasCandidatosv2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CANDIDATE1Entities : DbContext
    {
        public CANDIDATE1Entities()
            : base("name=CANDIDATE1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidate { get; set; }
        public virtual DbSet<Party> Party { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Vote> Vote { get; set; }
    }
}
