//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasCandidatosv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Vote = new HashSet<Vote>();
        }
    
        public int ID_Candidate { get; set; }
        public string NA_FirstName { get; set; }
        public string NA_LastName { get; set; }
        public string NA_MothersMaidenName { get; set; }
        public System.DateTime DA_Birth { get; set; }
        public string NA_Sex { get; set; }
        public string NA_Address { get; set; }
        public int NU_SocialSecurity { get; set; }
        public string NA_Education { get; set; }
        public string NA_Religion { get; set; }
        public string NA_Ethnicity { get; set; }
        public string NA_ActualPosition { get; set; }
        public int ID_Party { get; set; }
    
        public virtual Party Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Vote { get; set; }
    }
}
